name: arch_starters
description: A CLI tool to bootstrap Flutter projects with pre-configured architecture patterns (MVVM, Clean Architecture). Rapidly set up new projects with best practices.
version: 1.0.0
homepage: https://github.com/Ahmed-lashari/arch-starters
repository: https://github.com/Ahmed-lashari/arch-starters
issue_tracker: https://github.com/Ahmed-lashari/arch-starters/issues


environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  http: ^1.6.0
  archive: ^4.0.7
  path: ^1.9.1
  ansi_styles: ^0.3.2+1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  arch_starters: